version: '3'
services:
  hexo:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      - PUBLIC_HEXO_GITHUB_URL=https://github.com/zxfandyy/docker-hexo.git
    entrypoint:
      - sh
      - /build_and_run.sh
